### ISSUE TITLE
看起来没有使用说明

### ISSUE THREAD

**Issue by copurxia** [Mcayear/koishi-plugin-webhook-trigger-action#1]
想问一下设置监听地址之后的webhook地址应该是什么

**Comment by Mcayear** [comment]
是 baseUrl+listenerUrl

假设koishi面板地址是 https://koishiwebhookplugin.com

那么下面的配置中可以get请求https://koishiwebhookplugin.com/api/sendTestMsg
来让机器人向QQ `10001` 发送消息
![Screenshot_20230812_233015_edit_729570627541167](https://github.com/Mcayear/koishi-plugin-webhook-trigger-action/assets/48203962/8fe7dd64-3cdc-4872-a6da-a932cf3fb5f2)
![Screenshot_20230812_233021_edit_729588386434129](https://github.com/Mcayear/koishi-plugin-webhook-trigger-action/assets/48203962/40f4cb0b-8ab9-4a41-a4fd-e4e65cb37d80)

**Comment by copurxia** [comment]
万分感谢 ，原来是少了个/
